export const STATUS_CODE_UNAUTHORIZED = 401
export const STATUS_CODE_UNPROCESSABLE_ENTITY = 422
export const STATUS_CODE_PERMISSIONS_DENIED = 403
export const STATUS_CODE_INTERNAL_SERVER_ERROR = 500
export const STATUS_CODE_NOT_FOUND = 404